### ISSUE TITLE
I have tried everything but still get the same error

### ISSUE THREAD

**Issue by gamingmastyer** [Conjuringil/Pterodactyl-Theme-Library#2]
I follow the steps provided on github and on you website and couldn't resolve this error. If somebody could assist me i would be grateful. Thanks in advance.
![image](https://user-images.githubusercontent.com/68829360/105169561-9bb88700-5b13-11eb-9ad4-0a2a77410867.png)

**Comment by gamingmastyer** [comment]
I have joined the discord my user is Hoffao77#1337 and my panel version is 1.2.1

**Comment by Conjuringil** [comment]
I believe you got help in the discord server but if not run the command below then build the panel.

yarn add @emotion/react
